# Generated by Django 5.1.3 on 2024-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_remove_product_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='products.category'),
        ),
    ]
